// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article_list: dynamic(() => import("./ArticleList")),
  banner: dynamic(() => import("./Banner")),
};
